name: CodeRabbit Review

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run CodeRabbit Review
        uses: coderabbitai/coderabbit-action@v1
        with:
          config: coderabbit.yaml
          github_token: ${{ secrets.GITHUB_TOKEN }}
